apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo-stack.fullname" . }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo-express

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo-express

    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}"

          ports:
            - containerPort: 8081

          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "{{ .Release.Name }}-mongodb"

            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "{{ .Values.mongoExpress.mongodb.username }}"

            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "{{ .Values.mongoExpress.mongodb.password }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-stack.fullname" . }}-mongodb

spec:
  type: {{ .Values.mongoExpress.service.type }}

  selector:
    app: {{ .Release.Name }}-mongo-express

  ports:
    - protocol: TCP
      port: {{ .Values.mongoExpress.service.port }}
      targetPort: 8081
      nodePort: {{ .Values.mongoExpress.service.nodePort }}